@startuml
participant "Docker Container" as DC
collections "Readers" as R
participant "Load Balancer" as LB
participant "Worker Pool Supervisor" as PS
collections "Worker Printers" as PW
participant "Profanity Filter" as PF
participant "Sentiment Score" as SS
participant "Batcher" as B
participant "Console" as C

DC -> R: SSE with tweet
R -> LB: Binary tweet
LB -> PS: Binary tweet and worker nr
PS -> PW: Binary tweet
PW -> PF: Tweet text + Engagement ratio
PF -> PW: Tweet text + Engagement ratio
PW -> SS: Tweet text + Engagement ratio
SS -> PW: Tweet text + Engagement ratio+ Sentiment Score
PW -> C: Tweet text + Engagement ratio+ Sentiment Score
PW -> B: Filtered Tweet text + Engagement ratio+ Sentiment Score
B -> C: Batched Filtered Tweet text + Engagement ratio+ Sentiment Score
@enduml